apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "f5-bigip-ctlr.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "f5-bigip-ctlr.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "-" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "f5-bigip-ctlr.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - args:
        - --log-level
        - {{ .Values.args.log_level }}
        - --bigip-partition
        - {{ .Values.args.partition }}
        - --bigip-url
        - {{ .Values.args.bigip_url }}
        - --bigip-username
        - {{ .Values.args.bigip_username }}
        - --bigip-password
        - {{ .Values.args.bigip_password }}
        - --verify-interval
        - {{ .Values.args.verify_interval }}
        - --node-poll-interval
        - {{ .Values.args.node_poll_interval }}
        command:
        - /app/bin/k8s-bigip-ctlr
        image: "{{ .Values.image.user }}/{{ .Values.image.repo }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ template "f5-bigip-ctlr.name" . }}
